### ISSUE TITLE
Suggestion: require value property to avoid collisions when nesting

### ISSUE THREAD

**Issue by OliverJAsh** [pelotom/unionize#46]
When a union is nested inside a union, without a `value` property specified, the two values will collide:

E.g.

https://stackblitz.com/edit/typescript-ef4lbo?file=index.ts

``` ts
import { unionize, ofType } from 'unionize';

const InsideFoo = unionize({
  Bar: ofType<{ bar: number }>(),
});
type InsideFoo = typeof InsideFoo._Union;
const A = unionize({
  Foo: ofType<InsideFoo>(),
});

const a = A.Foo(InsideFoo.Bar({ bar: 1 }));

console.log(JSON.stringify(a))
```

Logs:

``` ts
{"bar":1,"tag":"Foo"}
```

As you can see, the tag for the nested union is lost, and the value for the nested union is merged with the value for the parent union.

We can fix this by specifying a `value` property:

``` ts
import { unionize, ofType } from 'unionize';

const InsideFoo = unionize({
  Bar: ofType<{ bar: number }>(),
}, { value: 'value' });
type InsideFoo = typeof InsideFoo._Union;
const A = unionize({
  Foo: ofType<InsideFoo>(),
}, { value: 'value' });

const a = A.Foo(InsideFoo.Bar({ bar: 1 }));

console.log(JSON.stringify(a))
```

Logs:

```
{"tag":"Foo","value":{"tag":"Bar","value":{"bar":1}}}
```

For this reason, I think that the `value` property should be required. I always forget to add one, and then run into these issues. Ideally I wouldn't have to specify a `value` property each time I use `unionize`.

Related code: https://github.com/pelotom/unionize/blob/f6ebfa50177aa3fdb724378c158e400c72d0d625/src/index.ts#L115

**Comment by pelotom** [comment]
That would preclude being able to model unions where the non-tag properties are all spread onto the top level object, rather than isolated under a single value property, which is a significant backwards-breaking change. Personally I use multi-value unions everywhere in my code, so I wouldn't want to lose that capability. I'd rather look for a way to statically enforce that you can't nest multi-value unions (unless they have non-conflicting tag/value properties?)

**Comment by OliverJAsh** [comment]
I'm not sure sure what you mean by multi-value unions?

**Comment by pelotom** [comment]
Multi-value:

```ts
type Foo =
  | { tag: 'bar'; a: number; b: boolean }
  | { tag: 'baz'; x: string; };
```

Single-value:

```ts
type Foo =
  | { tag: 'bar'; value: { a: number; b: boolean } }
  | { tag: 'baz'; value: { x: string; } };
```

The latter is something you would probably never write if you were doing it by hand (unless required to do so by an convention like Redux') because it's more annoying to work with outside of the `unionize` functions. But your proposal as I understand it would make the latter type of union the only kind we could model.

**Comment by OliverJAsh** [comment]
Thanks for clarifying!

I understand that my proposal would require all union value references to be updated, e.g. from `bar.x` to `bar.value.x`, which would be a breaking change. Is that the main breaking change you are alluding to, or something else? Are there other breaking changes this would cause?

> Personally I use multi-value unions everywhere in my code, so I wouldn't want to lose that capability.

As I understand it, the union members could still have multiple values, but these members would be inside of `value` (e.g. using an interface type). Other than the breaking change above, would this remove any flexibility? 🤔 

Sorry if I'm being slow on this one…

**Comment by pelotom** [comment]
> Thanks for clarifying!
> 
> I understand that my proposal would require all union value references to be updated, e.g. from `bar.x` to `bar.value.x`, which would be a breaking change. Is that the main breaking change you are alluding to, or something else? Are there other breaking changes this would cause?

Nope, that's the change I'm referring to.

> As I understand it, the union members could still have multiple values, but these members would be inside of `value` (e.g. using an interface type). Other than the breaking change above, would this remove any flexibility? 🤔

Yes, you can always nest multiple values under the singleton `value` property, but as I said above, it results types that are more convoluted than what you'd write if you were doing it by hand. As long as you're using only the `unionize` functions to manipulate such values it makes no difference, but as soon as you need to work directly with the instances of such a type it's just a little more annoying. For example writing a `switch` statement, which is sometimes more convenient because it allows handling several cases simultaneously:

```ts
switch (u.tag) {
  case 'foo':
  case 'bar':
    return u.value.a + u.value.b
  case 'baz':
    return u.value.x + u.value.y
}
```

it's nicer if you don't have to type all those `.value`s everywhere. Certainly you can get the job done with a single value prop, it's just not quite as nice to work with.

Then also there are situations where for the sake of working with a particular API you need be able to support more than one value property on the variants, for example in Redux there's the `error` property in addition to `value`.

**Comment by joshburgess** [comment]
> Multi-value:
> 
> ```ts
> type Foo =
>   | { tag: 'bar'; a: number; b: boolean }
>   | { tag: 'baz'; x: string; };
> ```

Wait, so this is exactly what I wanted to be able to do to use `meta` and `error` keys with Redux. How do you do this with unionize?

**Comment by pelotom** [comment]
@joshburgess 

```ts
const Foo = unionize({
  bar: ofType<{ a: number; b: boolean }>(),
  baz: ofType<{ x: string }>(),
});
```

**Comment by pelotom** [comment]
@joshburgess 

>When doing that, all of that is still lumped under the `value` prop, isn't it?

no... there is no value prop unless you specify one in the second parameter to `unionize`, e.g.

```ts
const Foo = unionize({
  bar: ofType<{ a: number; b: boolean }>(),
  baz: ofType<{ x: string }>(),
}, { value: 'value' });
```

**Comment by OliverJAsh** [comment]
I just ran into this again:

``` ts
type ContentProps = {
  tag: string;
};

const ContentMode = unionize({
  Content: ofType<ContentProps>(),
});
type ContentMode = typeof ContentMode._Union;

// no error, what's going on?!!
ContentMode.Content()
```

This is quite nasty. I really think the value property should be required and/or defined by default, to avoid nasty collisions like this.

**Comment by pelotom** [comment]
I believe this was also fixed by #56, no?

**Comment by OliverJAsh** [comment]
I don't believe so. My example in the original post still applies I think?

**Comment by pelotom** [comment]
@OliverJAsh this no longer compiles since #56:

```ts
const InsideFoo = unionize({
  Bar: ofType<{ bar: number }>(),
});
type InsideFoo = typeof InsideFoo._Union;
const A = unionize({
  Foo: ofType<InsideFoo>(),
});
```

You are forced to specify either a) a `tag` prop other than `"tag"` for `InsideFoo` or b) a `value` prop for `A`.

**Comment by OliverJAsh** [comment]
You're right. Amazing! Nice one @karol-majewski
