### ISSUE TITLE
Match case not infering/enforcing return value of function

### ISSUE THREAD

**Issue by MainShayne233** [pelotom/unionize#59]
It appears that the return type of match clauses isn't strongly checked/inferred by the return type of the function.

[In this example](https://codesandbox.io/s/react-typescript-playground-bpq8p?from-embed), you can see that the `INCREMENT_COUNT` match clause function is not returning a type of `StoreState`, but no compiler error is thrown. However, the `DECREMENT_COUNT` clause function explicitly declares that it is returning a `StoreState` type, and a compiler error is thrown.

Not sure if it is possible to make this return type inferred somehow, but it'd be nice to not have to remember to explicitly declare the return type of each match clause.

P.S. I absolutely love this library, and appreciate all the work that has been done for it. :smile: :heart:

**Comment by pelotom** [comment]
The problem is that

```ts
{
  count: state.count + 1,
  invalidProperty: "i shouldn't be here"
  // everything is fine
}
```

_is_ a perfectly valid `StoreState` due to structural subtyping. Excess property checking makes a best effort to help you not provide properties in a literal that can't possibly be subsequently accessed in a type safe manner, but it only works when you are directly assigning a literal to a variable or return value of a known type (the latter is what you're doing in the `DECREMENT_COUNT` case). I'm doubtful much can be done about this until TypeScript is able to express [exact types](https://github.com/microsoft/TypeScript/issues/12936).

Glad you're finding the library useful otherwise!

**Comment by MainShayne233** [comment]
@pelotom Makes sense! Thanks for the clarification there! Wanted to make sure it was probably a limitation of TypeScript versus something that could be changes in the library.
